### ISSUE TITLE
Export jpg bug

### ISSUE THREAD

**Issue by k4waiiiii** [flathub/org.inkscape.Inkscape#123] opened 2022-05-25 11:37 UTC
Export sucessfull but file not appear. Inkscape 1.2

**Comment by jfacemyer** [comment] 2022-05-25 11:48
Same here. Just updated to see if this was fixed, it's not.

**Comment by hfiguiere** [comment] 2022-05-25 15:59
you don't say where you export to. I can't really see from here.

**Comment by jfacemyer** [comment] 2022-05-25 16:19
Same workflow for exporting works on the official app image, but not the flatpak from flathub.

**Comment by hfiguiere** [comment] 2022-05-25 17:06
You still don't say *where* you are trying to save the file.

**Comment by k4waiiiii** [comment] 2022-05-25 18:36
I'm just normal user. So, I install Inkscape from flathub and then open it, make some design and finish it. After that I export to jpg and file not appear so I report this bug.

**Comment by nathanal** [comment] 2022-05-26 02:12
In the future, please link to your original report and also add all the information over. The Inkscape report refers to https://gitlab.com/inkscape/inbox/-/issues/7048

When trying to save, it appears to succeed but no jpg is created. I also can confirm it happens to me. 

This matches an issue we faced in https://gitlab.com/inkscape/extensions/-/issues/416, which was due to a python-Pillow bug (https://github.com/python-pillow/Pillow/pull/5665).

Running the following, it looks like we are on an older version of Pillow that experiences the bug (The pillow fix was merged in ab6efcb925f615d153538e84780f093f7f9f8df2, https://github.com/python-pillow/Pillow/pull/5665, git describe --tags ab6efcb925f615d153538e84780f093f7f9f8df2 gives 8.4.0-122-gab6efcb9,)

```
flatpak  run --command=sh org.inkscape.Inkscape
python3
>>> import PIL
>>> PIL.__version__
'8.3.2'
>>> 
```

I assume the solution would be to upgrade the pillow version, is it okay to upgrade to 9.x? (It doesn't look like the fix is in 8.x yet)

**Comment by hfiguiere** [comment] 2022-05-26 02:19
Upgrading to Pillow 9 then.

**Comment by hfiguiere** [comment] 2022-05-26 02:29
tbf JPEG worked fine for me, I couldn't reproduce.

**Comment by nathanal** [comment] 2022-05-26 05:02
I can't explain why jpeg worked for you (I don't see why the bug shouldn't affect everyone. Can you open the jpg file?), but testing the version linked by flathubbot, can confirm the PR fixes the issue :fire:

**Closed** 2022-05-26 12:26 UTC

**Comment by hfiguiere** [comment] 2022-05-26 15:23
yes I checked the JPEG was valid. Anyway. The new build should be available in a few hours.

**Comment by k4waiiiii** [comment] 2022-05-27 00:34
JPG export is successful now. Thank you for fixing.
