### ISSUE TITLE
Package Inkscape Nightly

### ISSUE THREAD

**Issue by boredsquirrel** [flathub/org.inkscape.Inkscape#164] opened 2024-04-04 21:06 UTC
Inkscape supports PPA, Snap and Appimage... Yeah.

The port to GTK4 which will be quite a change, for testing purposes flatpakking would for sure be useful.

This could be done via flathub-beta or an external unofficial repo like [unofficial firefox nightly flatpak](https://gitlab.com/projects261/firefox-nightly-flatpak) using the latest git commit from [the Inkscape Gitlab](https://gitlab.com/inkscape/inkscape/).

I would like to contribute but never packaged a Flatpak.

**Comment by hfiguiere** [comment] 2024-04-04 21:11
duplicate of #163 

Flathub is not for Nightlies.

When there is a beta, it will land on beta.

**Closed** 2024-04-04 21:11 UTC
